version: '3.7'
services:
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: dynamoflow-tests-dynamodb
    hostname: dynamodb
    restart: always
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb -port 8000"
