version: '3.7'
services:
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: dynaflow-tests-dynamodb
    hostname: dynamodb
    restart: always
    ports:
      - 8000:8000
    #volumes:
    #  - ./dynamodb_data:/home/dynamodblocal/data
    #  "-dbPath ./data"
    command: "-jar DynamoDBLocal.jar"
